// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkgdotyusfxrqhisskfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrZ2RvdHl1c2Z4cnFoaXNza2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjMxMDYsImV4cCI6MjA2MDk5OTEwNn0.tvAtAsF1CPlMHzyOSBJP4iTASCl0c3xQ_Fr7ikC9vzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);